SS_SPIKE_CLIENT_ID: bwwIB0gSS0xay_odirl0OCAJ3gUlXkKMKijbDY_e
SS_SPIKE_CLIENT_SECRET: 9FlWUMIVykj9r9iZoRq9o~1v4WP~1GJ49qlaAX7K3xXKIK6KePmRY~9B1X6EQPC00Hg~FBdTsU_EPNqmeZmZ5DbJ3feYwLN1hQg9
SS_USE_REDIS: true
SS_REDIS_HOST: 127.0.0.1
SS_REDIS_PORT: 6379
SS_REDIS_PASSWORD: mozart
SS_SPIKE_TOKEN_URL: https://ospike.northeurope.cloudapp.azure.com/oauth2/token
SS_SPIKE_PUBKEY_PATH: https://ospike.northeurope.cloudapp.azure.com/.well-known/publickey.pem
SS_SPIKE_PUBLIC_KEY_FULL_PATH: /home/barak/Desktop/SuperNova/spike-service/src/utils/publickey.pem
SS_SHMUEL_AUDIENCE: shmuel
SS_KARTOFFEL_AUDIENCE: kartoffel
SS_GRANT_TYPE: client_credentials
SS_HOST: 0.0.0.0
SS_PORT: 8080
SS_LOG_PATH: ./logs

RS_MONGO_URL: mongodb://localhost:27017/supernova
RS_HOST: 0.0.0.0
RS_PORT: 8081
RS_NS_URL: 0.0.0.0:8084
RS_TS_URL: 0.0.0.0:8086
RS_LOG_PATH: ./logs

KS_HOST: 0.0.0.0
KS_PORT: 8082
KS_KARTOFFEL_URL: http://52.188.158.174:7709
KS_SS_URL: 0.0.0.0:8080
KS_USE_FAKER: true
KS_KARTOFFEL_AUDIENCE: kartoffel
KS_SPIKE_TOKEN_REFRESH_HOURS: 24
KS_COMMANDER_RANKS: aaaa,bbbb,cccc,ssss
KS_ROOT_ID: 611b5c58a7a257532f054a4b
KS_LOG_PATH: ./logs

EXS_RS_URL: 0.0.0.0:8081
EXS_PS_URL: 0.0.0.0:8083
EXS_APS_URL: 0.0.0.0:8085
EXS_EVERY_HOUR: 1
EXS_CRON_JOB: false
EXS_LOG_PATH: ./logs

WLS_APS_URL: 0.0.0.0:8085
WLS_HOUR: 0
WLS_MINUTE: 0
WLS_CRON_JOB: false
WLS_LOG_PATH: ./logs

PS_HOST: 0.0.0.0
PS_PORT: 8083
PS_QUEUE_API_URL: http://20.199.120.227:3000
PS_RS_URL: 0.0.0.0:8081
PS_DEV_MODE: true
PS_SHMUEL_AUDIENCE: shmuel
PS_SS_URL: 0.0.0.0:8080
PS_SPIKE_TOKEN_REFRESH_HOURS: 24
PS_OLD_DOMAIN: oldDomain
PS_NEW_DOMAIN: newDomain
PS_LOG_PATH: ./logs

AS_PORT: 8080
AS_ENDPOINT: http://localhost:9000/auth
AS_ALLOWED_ORIGINS: http://localhost/
AS_TOKEN: sp-token
AS_SECRET_KEY: superNova
AS_TOKEN_DAYS_EXPIRES: 30
AS_PROFILE_EXTRACTOR_ID: id
AS_PROFILE_EXTRACTOR_MAIL: mail
AS_PROFILE_EXTRACTOR_FIRST_NAME: givenName
AS_PROFILE_EXTRACTOR_LAST_NAME: surName
AS_PROFILE_EXTRACTOR_JOB: job
AS_STRATEGY: shraga
AS_SHRAGA_URL: https://shraga-prod.northeurope.cloudapp.azure.com
AS_SHRAGA_USE_ENRICH_ID: true
AS_SHRAGA_PROVIDERS: Genesis
AS_CLIENT_ENDPOINT: http://localhost:2000
AS_LOG_PATH: ./logs

GATEWAY_HOST: 0.0.0.0
GATEWAY_PORT: 8080
GATEWAY_RS_URL: 0.0.0.0:8081
GATEWAY_KS_URL: 0.0.0.0:8082
GATEWAY_PS_URL: 0.0.0.0:8083
GATEWAY_NS_URL: 0.0.0.0:8084
GATEWAY_APS_URL: 0.0.0.0:8085
GATEWAY_BS_URL: 0.0.0.0:8087
GATEWAY_AS_URL: 0.0.0.0:9000
GATEWAY_TOKEN: sp-token
GATEWAY_SECRET_KEY: superNova
GATEWAY_APM_URL: http://52.169.23.32:8200
GATEWAY_SPIKE_AUDIENCE_ID: bwwIB0gSS0xay_odirl0OCAJ3gUlXkKMKijbDY_e
GATEWAY_SPIKE_PUBLIC_KEY_FULL_PATH: /home/barak/Desktop/SuperNova/spike-service/src/utils/publickey.pem
GATEWAY_WRITE_SCOPE_NAME: write
GATEWAY_LOG_PATH: ./logs
GATEWAY_USE_APM: false
GATEWAY_BS_FOLDER_PATH: ../bulk-service/src/excelFilesExample

NS_HOST: 0.0.0.0
NS_PORT: 8084
NS_MONGO_URL: mongodb://localhost:27017/supernova
NS_LOG_PATH: ./logs

APS_HOST: 0.0.0.0
APS_PORT: 8085
APS_MONGO_URL: mongodb://localhost:27017/supernova
APS_KS_URL: 0.0.0.0:8082
APS_RS_URL: 0.0.0.0:8081
APS_COMMANDER_RANKS: aaaa,bbbb,cccc,ssss
APS_LOG_PATH: ./logs

TS_HOST: 0.0.0.0
TS_PORT: 8086
TS_MONGO_URL: mongodb://localhost:27017/supernova
TS_SOLDIER: soldier
TS_RESERVED: reserved
TS_CIVILIAN: civilian
TS_GOAL_USER: goalUser
TS_KS_URL: 0.0.0.0:8082
TS_GENERAL_UNIT_ID: google
TS_NEED_INIT: true
TS_INIT_EMPTY_ARRAYS: true
TS_INIT_UNIT_HIERARCHIES: גוגל העולמית/גוגל,אמאזון העולמית/אמאזון
TS_INIT_UNIT_NAMES: גוגל,אמאזון
TS_INIT_IDS: google,amazon
TS_INIT_PREFIXES: 100,200
TS_INIT_COUNTERS: 1,1
TS_SUFFIXES_OLD_DOMAIN: gmail.com,amazon.com
TS_SUFFIXES_NEW_DOMAIN: newDomain.com,newDomain.com
TS_LOG_PATH: ./logs

BS_HOST: 0.0.0.0
BS_PORT: 8087
BS_RS_URL: 0.0.0.0:8081
BS_LOG_PATH: ./logs
 #Set only in docker
# BS_FOLDER_PATH: excelFilesExample

POS_RS_URL: 0.0.0.0:8081
POS_ENTITY_IDS: 111111111111111111111111,222222222222222222222222,333333333333333333333333,444444444444444444444444
POS_GENERATE_COUNT: 50
POS_LOG_PATH: ./logs

KC_RS_URL: 0.0.0.0:8081
KC_TS_URL: 0.0.0.0:8086
KC_KS_URL: 0.0.0.0:8082
KC_KAFKA_HOST: 127.0.0.1
KC_KAFKA_PORT: 9092
KC_LOG_PATH: /logs
KC_KAFKA_CONSUMER_TOPIC: requests


REACT_APP_BASE_URL: http://localhost:2000
REACT_TOKEN_NAME: sp-token

GLOBAL_STORE_LOGS: true
